# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Aditya Nagarajan
tagline:             Aspiring Data Scientist
url:                 http://adityanagara.github.io
paginate:            1
baseurl:             "http://adityanagara.github.io"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Aditya Nagarajan
  url:               https://twitter.com/adinagarajan
  email:             adinagarajan1@gmail.com
# List of pages to include at the top
pages_list:       
  About: '/about/'
#  Archive: '/archive/'

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/adityanagara/adityanagara.github.io
